### PR TITLE
Refactor localization and unit descriptions

### PR DESCRIPTION
**Pull request by osjc**
The "localization and units" proved to be too rigid for the changes I am doing right now. Here is a more flexible version with the added bonus of quite a bunch of code duplication in this piece of code removed.

### CODE REVIEW

**Comment by osjc** [comment]
Ok, the test of GitHub's ability to take an improved version of pull-requested commits was successful. No need to R.I.P a broken set of patches anymore.

**Comment by Foghrye4** [comment]
You can merge PR now by yourself.

**Comment by osjc** [comment]
Well, I can't merge anything as I don't have write access. Or, at least GitHub does not indicate I have write access.

**Comment by Foghrye4** [comment]
screenshot from 2018-01-22 19-58-14

**Comment by osjc** [comment]
Thank you for the pointer. It turns out I did not read my mail in a LOOOOOOONG while :smile: . And I did not expect my permissions to show up there :rofl:

Now GitHub says I can merge so I am going to take advantage of it.

**Comment by osjc** [comment]
Ok, it worked. 3 pull requests merged and more to go now.

A rule I am going to adopt is that I will submit a merge request first and leave it open for a couple of days ("cooldown"). If anyone is there and has some comments, he can comment on the request. I know, now there is nobody (educated guess - i took look at the traffic stats and saw only 2 unique visitors - you and me), but I can't be sure what is going to happen in the future and also it is a good habit to maintain for the future, especially when I found certain issues that might require to start tinkering with the minetest project itself (well, a workaround is possible but I can see how the minetest project itself would benefit from a more thorough solution).

**Pull request merged**
